### ISSUE TITLE
S2P test error

### ISSUE THREAD

**Issue by fanzz1208** [centreborelli/satnerf#37]
(s2p) root@f38ff6aacd8f:/workspace/satnerf# python3 eval_s2p.py JAX_068 /workspace/satnerf/datasets/root_dir/crops_rpcs_ba_v2/JAX_068 /workspace/satnerf/datasets/DFC2019 /workspace/satnerf/results/ --n_pairs 10
Output dir: /workspace/satnerf/results/s2p_dsms/JAX_068
10 heuristic pairs selected
Running s2p ! Pair 1 of 10...
...done
Running s2p ! Pair 2 of 10...
...done
Running s2p ! Pair 3 of 10...
...done
Running s2p ! Pair 4 of 10...
...done
Running s2p ! Pair 5 of 10...
...done
Running s2p ! Pair 6 of 10...
...done
Running s2p ! Pair 7 of 10...
...done
Running s2p ! Pair 8 of 10...
...done
Running s2p ! Pair 9 of 10...
...done
Running s2p ! Pair 10 of 10...
...done
Traceback (most recent call last):
  File "eval_s2p.py", line 320, in <module>
    fire.Fire(eval_s2p)
  File "/root/anaconda3/envs/s2p/lib/python3.6/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/s2p/lib/python3.6/site-packages/fire/core.py", line 473, in _Fire
    target=component.__name__)
  File "/root/anaconda3/envs/s2p/lib/python3.6/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "eval_s2p.py", line 258, in eval_s2p
    shutil.rmtree("s2p_tmp")
  File "/root/anaconda3/envs/s2p/lib/python3.6/shutil.py", line 477, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/root/anaconda3/envs/s2p/lib/python3.6/shutil.py", line 475, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: 's2p_tmp'

**Comment by fanzz1208** [comment]
"/mnt/cdisk/roger/Datasets/SatNeRF/root_dir/fullaoi_rpcs_ba_v1/JAX_068"
where "fullaoi_rpcs_ba_v1"?
